//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialCalculatorWebApp.LiveFinCalcRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/", ConfigurationName="LiveFinCalcRef.FinancialCalculatorWebServiceSoap")]
    public interface FinancialCalculatorWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name CalculateSimpleInterestResult from namespace http://myfinancialcalculatorwebservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myfinancialcalculatorwebservice.org/CalculateSimpleInterest", ReplyAction="*")]
        FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestResponse CalculateSimpleInterest(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myfinancialcalculatorwebservice.org/CalculateSimpleInterest", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestResponse> CalculateSimpleInterestAsync(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestRequest request);
        
        // CODEGEN: Generating message contract since element name CalculatePrincipalResult from namespace http://myfinancialcalculatorwebservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myfinancialcalculatorwebservice.org/CalculatePrincipal", ReplyAction="*")]
        FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalResponse CalculatePrincipal(FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myfinancialcalculatorwebservice.org/CalculatePrincipal", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalResponse> CalculatePrincipalAsync(FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalRequest request);
        
        // CODEGEN: Generating message contract since element name CalculateRateResult from namespace http://myfinancialcalculatorwebservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myfinancialcalculatorwebservice.org/CalculateRate", ReplyAction="*")]
        FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateResponse CalculateRate(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myfinancialcalculatorwebservice.org/CalculateRate", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateResponse> CalculateRateAsync(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateRequest request);
        
        // CODEGEN: Generating message contract since element name CalculateTimeResult from namespace http://myfinancialcalculatorwebservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myfinancialcalculatorwebservice.org/CalculateTime", ReplyAction="*")]
        FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeResponse CalculateTime(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myfinancialcalculatorwebservice.org/CalculateTime", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeResponse> CalculateTimeAsync(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateSimpleInterestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateSimpleInterest", Namespace="http://myfinancialcalculatorwebservice.org/", Order=0)]
        public FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestRequestBody Body;
        
        public CalculateSimpleInterestRequest() {
        }
        
        public CalculateSimpleInterestRequest(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/")]
    public partial class CalculateSimpleInterestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double principalAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double annualInterestRate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double timeInDays;
        
        public CalculateSimpleInterestRequestBody() {
        }
        
        public CalculateSimpleInterestRequestBody(double principalAmount, double annualInterestRate, double timeInDays) {
            this.principalAmount = principalAmount;
            this.annualInterestRate = annualInterestRate;
            this.timeInDays = timeInDays;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateSimpleInterestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateSimpleInterestResponse", Namespace="http://myfinancialcalculatorwebservice.org/", Order=0)]
        public FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestResponseBody Body;
        
        public CalculateSimpleInterestResponse() {
        }
        
        public CalculateSimpleInterestResponse(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/")]
    public partial class CalculateSimpleInterestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculateSimpleInterestResult;
        
        public CalculateSimpleInterestResponseBody() {
        }
        
        public CalculateSimpleInterestResponseBody(string CalculateSimpleInterestResult) {
            this.CalculateSimpleInterestResult = CalculateSimpleInterestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatePrincipalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculatePrincipal", Namespace="http://myfinancialcalculatorwebservice.org/", Order=0)]
        public FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalRequestBody Body;
        
        public CalculatePrincipalRequest() {
        }
        
        public CalculatePrincipalRequest(FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/")]
    public partial class CalculatePrincipalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double simpleInterest;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double annualInterestRate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double timeInDays;
        
        public CalculatePrincipalRequestBody() {
        }
        
        public CalculatePrincipalRequestBody(double simpleInterest, double annualInterestRate, double timeInDays) {
            this.simpleInterest = simpleInterest;
            this.annualInterestRate = annualInterestRate;
            this.timeInDays = timeInDays;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatePrincipalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculatePrincipalResponse", Namespace="http://myfinancialcalculatorwebservice.org/", Order=0)]
        public FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalResponseBody Body;
        
        public CalculatePrincipalResponse() {
        }
        
        public CalculatePrincipalResponse(FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/")]
    public partial class CalculatePrincipalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculatePrincipalResult;
        
        public CalculatePrincipalResponseBody() {
        }
        
        public CalculatePrincipalResponseBody(string CalculatePrincipalResult) {
            this.CalculatePrincipalResult = CalculatePrincipalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateRateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateRate", Namespace="http://myfinancialcalculatorwebservice.org/", Order=0)]
        public FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateRequestBody Body;
        
        public CalculateRateRequest() {
        }
        
        public CalculateRateRequest(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/")]
    public partial class CalculateRateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double principalAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double simpleInterest;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double timeInDays;
        
        public CalculateRateRequestBody() {
        }
        
        public CalculateRateRequestBody(double principalAmount, double simpleInterest, double timeInDays) {
            this.principalAmount = principalAmount;
            this.simpleInterest = simpleInterest;
            this.timeInDays = timeInDays;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateRateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateRateResponse", Namespace="http://myfinancialcalculatorwebservice.org/", Order=0)]
        public FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateResponseBody Body;
        
        public CalculateRateResponse() {
        }
        
        public CalculateRateResponse(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/")]
    public partial class CalculateRateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculateRateResult;
        
        public CalculateRateResponseBody() {
        }
        
        public CalculateRateResponseBody(string CalculateRateResult) {
            this.CalculateRateResult = CalculateRateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateTime", Namespace="http://myfinancialcalculatorwebservice.org/", Order=0)]
        public FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeRequestBody Body;
        
        public CalculateTimeRequest() {
        }
        
        public CalculateTimeRequest(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/")]
    public partial class CalculateTimeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double principalAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double simpleInterest;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double annualInterestRate;
        
        public CalculateTimeRequestBody() {
        }
        
        public CalculateTimeRequestBody(double principalAmount, double simpleInterest, double annualInterestRate) {
            this.principalAmount = principalAmount;
            this.simpleInterest = simpleInterest;
            this.annualInterestRate = annualInterestRate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateTimeResponse", Namespace="http://myfinancialcalculatorwebservice.org/", Order=0)]
        public FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeResponseBody Body;
        
        public CalculateTimeResponse() {
        }
        
        public CalculateTimeResponse(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/")]
    public partial class CalculateTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculateTimeResult;
        
        public CalculateTimeResponseBody() {
        }
        
        public CalculateTimeResponseBody(string CalculateTimeResult) {
            this.CalculateTimeResult = CalculateTimeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FinancialCalculatorWebServiceSoapChannel : FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinancialCalculatorWebServiceSoapClient : System.ServiceModel.ClientBase<FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap>, FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap {
        
        public FinancialCalculatorWebServiceSoapClient() {
        }
        
        public FinancialCalculatorWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinancialCalculatorWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialCalculatorWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialCalculatorWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestResponse FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap.CalculateSimpleInterest(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestRequest request) {
            return base.Channel.CalculateSimpleInterest(request);
        }
        
        public string CalculateSimpleInterest(double principalAmount, double annualInterestRate, double timeInDays) {
            FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestRequest inValue = new FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestRequest();
            inValue.Body = new FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestRequestBody();
            inValue.Body.principalAmount = principalAmount;
            inValue.Body.annualInterestRate = annualInterestRate;
            inValue.Body.timeInDays = timeInDays;
            FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestResponse retVal = ((FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap)(this)).CalculateSimpleInterest(inValue);
            return retVal.Body.CalculateSimpleInterestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestResponse> FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap.CalculateSimpleInterestAsync(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestRequest request) {
            return base.Channel.CalculateSimpleInterestAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestResponse> CalculateSimpleInterestAsync(double principalAmount, double annualInterestRate, double timeInDays) {
            FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestRequest inValue = new FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestRequest();
            inValue.Body = new FinancialCalculatorWebApp.LiveFinCalcRef.CalculateSimpleInterestRequestBody();
            inValue.Body.principalAmount = principalAmount;
            inValue.Body.annualInterestRate = annualInterestRate;
            inValue.Body.timeInDays = timeInDays;
            return ((FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap)(this)).CalculateSimpleInterestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalResponse FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap.CalculatePrincipal(FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalRequest request) {
            return base.Channel.CalculatePrincipal(request);
        }
        
        public string CalculatePrincipal(double simpleInterest, double annualInterestRate, double timeInDays) {
            FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalRequest inValue = new FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalRequest();
            inValue.Body = new FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalRequestBody();
            inValue.Body.simpleInterest = simpleInterest;
            inValue.Body.annualInterestRate = annualInterestRate;
            inValue.Body.timeInDays = timeInDays;
            FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalResponse retVal = ((FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap)(this)).CalculatePrincipal(inValue);
            return retVal.Body.CalculatePrincipalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalResponse> FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap.CalculatePrincipalAsync(FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalRequest request) {
            return base.Channel.CalculatePrincipalAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalResponse> CalculatePrincipalAsync(double simpleInterest, double annualInterestRate, double timeInDays) {
            FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalRequest inValue = new FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalRequest();
            inValue.Body = new FinancialCalculatorWebApp.LiveFinCalcRef.CalculatePrincipalRequestBody();
            inValue.Body.simpleInterest = simpleInterest;
            inValue.Body.annualInterestRate = annualInterestRate;
            inValue.Body.timeInDays = timeInDays;
            return ((FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap)(this)).CalculatePrincipalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateResponse FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap.CalculateRate(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateRequest request) {
            return base.Channel.CalculateRate(request);
        }
        
        public string CalculateRate(double principalAmount, double simpleInterest, double timeInDays) {
            FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateRequest inValue = new FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateRequest();
            inValue.Body = new FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateRequestBody();
            inValue.Body.principalAmount = principalAmount;
            inValue.Body.simpleInterest = simpleInterest;
            inValue.Body.timeInDays = timeInDays;
            FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateResponse retVal = ((FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap)(this)).CalculateRate(inValue);
            return retVal.Body.CalculateRateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateResponse> FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap.CalculateRateAsync(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateRequest request) {
            return base.Channel.CalculateRateAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateResponse> CalculateRateAsync(double principalAmount, double simpleInterest, double timeInDays) {
            FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateRequest inValue = new FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateRequest();
            inValue.Body = new FinancialCalculatorWebApp.LiveFinCalcRef.CalculateRateRequestBody();
            inValue.Body.principalAmount = principalAmount;
            inValue.Body.simpleInterest = simpleInterest;
            inValue.Body.timeInDays = timeInDays;
            return ((FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap)(this)).CalculateRateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeResponse FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap.CalculateTime(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeRequest request) {
            return base.Channel.CalculateTime(request);
        }
        
        public string CalculateTime(double principalAmount, double simpleInterest, double annualInterestRate) {
            FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeRequest inValue = new FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeRequest();
            inValue.Body = new FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeRequestBody();
            inValue.Body.principalAmount = principalAmount;
            inValue.Body.simpleInterest = simpleInterest;
            inValue.Body.annualInterestRate = annualInterestRate;
            FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeResponse retVal = ((FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap)(this)).CalculateTime(inValue);
            return retVal.Body.CalculateTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeResponse> FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap.CalculateTimeAsync(FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeRequest request) {
            return base.Channel.CalculateTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeResponse> CalculateTimeAsync(double principalAmount, double simpleInterest, double annualInterestRate) {
            FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeRequest inValue = new FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeRequest();
            inValue.Body = new FinancialCalculatorWebApp.LiveFinCalcRef.CalculateTimeRequestBody();
            inValue.Body.principalAmount = principalAmount;
            inValue.Body.simpleInterest = simpleInterest;
            inValue.Body.annualInterestRate = annualInterestRate;
            return ((FinancialCalculatorWebApp.LiveFinCalcRef.FinancialCalculatorWebServiceSoap)(this)).CalculateTimeAsync(inValue);
        }
    }
}
