//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialCalculatorWebApp.FinCalcReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/", ConfigurationName="FinCalcReference.FinancialCalculatorWebServiceSoap")]
    public interface FinancialCalculatorWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name CalculateSimpleInterestResult from namespace http://myfinancialcalculatorwebservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myfinancialcalculatorwebservice.org/CalculateSimpleInterest", ReplyAction="*")]
        FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestResponse CalculateSimpleInterest(FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myfinancialcalculatorwebservice.org/CalculateSimpleInterest", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestResponse> CalculateSimpleInterestAsync(FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestRequest request);
        
        // CODEGEN: Generating message contract since element name CalculatePrincipalResult from namespace http://myfinancialcalculatorwebservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myfinancialcalculatorwebservice.org/CalculatePrincipal", ReplyAction="*")]
        FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalResponse CalculatePrincipal(FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myfinancialcalculatorwebservice.org/CalculatePrincipal", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalResponse> CalculatePrincipalAsync(FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalRequest request);
        
        // CODEGEN: Generating message contract since element name CalculateRateResult from namespace http://myfinancialcalculatorwebservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myfinancialcalculatorwebservice.org/CalculateRate", ReplyAction="*")]
        FinancialCalculatorWebApp.FinCalcReference.CalculateRateResponse CalculateRate(FinancialCalculatorWebApp.FinCalcReference.CalculateRateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myfinancialcalculatorwebservice.org/CalculateRate", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialCalculatorWebApp.FinCalcReference.CalculateRateResponse> CalculateRateAsync(FinancialCalculatorWebApp.FinCalcReference.CalculateRateRequest request);
        
        // CODEGEN: Generating message contract since element name CalculateTimeResult from namespace http://myfinancialcalculatorwebservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myfinancialcalculatorwebservice.org/CalculateTime", ReplyAction="*")]
        FinancialCalculatorWebApp.FinCalcReference.CalculateTimeResponse CalculateTime(FinancialCalculatorWebApp.FinCalcReference.CalculateTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myfinancialcalculatorwebservice.org/CalculateTime", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialCalculatorWebApp.FinCalcReference.CalculateTimeResponse> CalculateTimeAsync(FinancialCalculatorWebApp.FinCalcReference.CalculateTimeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateSimpleInterestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateSimpleInterest", Namespace="http://myfinancialcalculatorwebservice.org/", Order=0)]
        public FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestRequestBody Body;
        
        public CalculateSimpleInterestRequest() {
        }
        
        public CalculateSimpleInterestRequest(FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/")]
    public partial class CalculateSimpleInterestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double principalAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double annualInterestRate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double timeInDays;
        
        public CalculateSimpleInterestRequestBody() {
        }
        
        public CalculateSimpleInterestRequestBody(double principalAmount, double annualInterestRate, double timeInDays) {
            this.principalAmount = principalAmount;
            this.annualInterestRate = annualInterestRate;
            this.timeInDays = timeInDays;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateSimpleInterestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateSimpleInterestResponse", Namespace="http://myfinancialcalculatorwebservice.org/", Order=0)]
        public FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestResponseBody Body;
        
        public CalculateSimpleInterestResponse() {
        }
        
        public CalculateSimpleInterestResponse(FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/")]
    public partial class CalculateSimpleInterestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculateSimpleInterestResult;
        
        public CalculateSimpleInterestResponseBody() {
        }
        
        public CalculateSimpleInterestResponseBody(string CalculateSimpleInterestResult) {
            this.CalculateSimpleInterestResult = CalculateSimpleInterestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatePrincipalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculatePrincipal", Namespace="http://myfinancialcalculatorwebservice.org/", Order=0)]
        public FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalRequestBody Body;
        
        public CalculatePrincipalRequest() {
        }
        
        public CalculatePrincipalRequest(FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/")]
    public partial class CalculatePrincipalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double simpleInterest;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double annualInterestRate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double timeInDays;
        
        public CalculatePrincipalRequestBody() {
        }
        
        public CalculatePrincipalRequestBody(double simpleInterest, double annualInterestRate, double timeInDays) {
            this.simpleInterest = simpleInterest;
            this.annualInterestRate = annualInterestRate;
            this.timeInDays = timeInDays;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatePrincipalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculatePrincipalResponse", Namespace="http://myfinancialcalculatorwebservice.org/", Order=0)]
        public FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalResponseBody Body;
        
        public CalculatePrincipalResponse() {
        }
        
        public CalculatePrincipalResponse(FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/")]
    public partial class CalculatePrincipalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculatePrincipalResult;
        
        public CalculatePrincipalResponseBody() {
        }
        
        public CalculatePrincipalResponseBody(string CalculatePrincipalResult) {
            this.CalculatePrincipalResult = CalculatePrincipalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateRateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateRate", Namespace="http://myfinancialcalculatorwebservice.org/", Order=0)]
        public FinancialCalculatorWebApp.FinCalcReference.CalculateRateRequestBody Body;
        
        public CalculateRateRequest() {
        }
        
        public CalculateRateRequest(FinancialCalculatorWebApp.FinCalcReference.CalculateRateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/")]
    public partial class CalculateRateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double principalAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double simpleInterest;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double timeInDays;
        
        public CalculateRateRequestBody() {
        }
        
        public CalculateRateRequestBody(double principalAmount, double simpleInterest, double timeInDays) {
            this.principalAmount = principalAmount;
            this.simpleInterest = simpleInterest;
            this.timeInDays = timeInDays;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateRateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateRateResponse", Namespace="http://myfinancialcalculatorwebservice.org/", Order=0)]
        public FinancialCalculatorWebApp.FinCalcReference.CalculateRateResponseBody Body;
        
        public CalculateRateResponse() {
        }
        
        public CalculateRateResponse(FinancialCalculatorWebApp.FinCalcReference.CalculateRateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/")]
    public partial class CalculateRateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculateRateResult;
        
        public CalculateRateResponseBody() {
        }
        
        public CalculateRateResponseBody(string CalculateRateResult) {
            this.CalculateRateResult = CalculateRateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateTime", Namespace="http://myfinancialcalculatorwebservice.org/", Order=0)]
        public FinancialCalculatorWebApp.FinCalcReference.CalculateTimeRequestBody Body;
        
        public CalculateTimeRequest() {
        }
        
        public CalculateTimeRequest(FinancialCalculatorWebApp.FinCalcReference.CalculateTimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/")]
    public partial class CalculateTimeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double principalAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double simpleInterest;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double annualInterestRate;
        
        public CalculateTimeRequestBody() {
        }
        
        public CalculateTimeRequestBody(double principalAmount, double simpleInterest, double annualInterestRate) {
            this.principalAmount = principalAmount;
            this.simpleInterest = simpleInterest;
            this.annualInterestRate = annualInterestRate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateTimeResponse", Namespace="http://myfinancialcalculatorwebservice.org/", Order=0)]
        public FinancialCalculatorWebApp.FinCalcReference.CalculateTimeResponseBody Body;
        
        public CalculateTimeResponse() {
        }
        
        public CalculateTimeResponse(FinancialCalculatorWebApp.FinCalcReference.CalculateTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myfinancialcalculatorwebservice.org/")]
    public partial class CalculateTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculateTimeResult;
        
        public CalculateTimeResponseBody() {
        }
        
        public CalculateTimeResponseBody(string CalculateTimeResult) {
            this.CalculateTimeResult = CalculateTimeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FinancialCalculatorWebServiceSoapChannel : FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinancialCalculatorWebServiceSoapClient : System.ServiceModel.ClientBase<FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap>, FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap {
        
        public FinancialCalculatorWebServiceSoapClient() {
        }
        
        public FinancialCalculatorWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinancialCalculatorWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialCalculatorWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialCalculatorWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestResponse FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap.CalculateSimpleInterest(FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestRequest request) {
            return base.Channel.CalculateSimpleInterest(request);
        }
        
        public string CalculateSimpleInterest(double principalAmount, double annualInterestRate, double timeInDays) {
            FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestRequest inValue = new FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestRequest();
            inValue.Body = new FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestRequestBody();
            inValue.Body.principalAmount = principalAmount;
            inValue.Body.annualInterestRate = annualInterestRate;
            inValue.Body.timeInDays = timeInDays;
            FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestResponse retVal = ((FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap)(this)).CalculateSimpleInterest(inValue);
            return retVal.Body.CalculateSimpleInterestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestResponse> FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap.CalculateSimpleInterestAsync(FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestRequest request) {
            return base.Channel.CalculateSimpleInterestAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestResponse> CalculateSimpleInterestAsync(double principalAmount, double annualInterestRate, double timeInDays) {
            FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestRequest inValue = new FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestRequest();
            inValue.Body = new FinancialCalculatorWebApp.FinCalcReference.CalculateSimpleInterestRequestBody();
            inValue.Body.principalAmount = principalAmount;
            inValue.Body.annualInterestRate = annualInterestRate;
            inValue.Body.timeInDays = timeInDays;
            return ((FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap)(this)).CalculateSimpleInterestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalResponse FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap.CalculatePrincipal(FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalRequest request) {
            return base.Channel.CalculatePrincipal(request);
        }
        
        public string CalculatePrincipal(double simpleInterest, double annualInterestRate, double timeInDays) {
            FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalRequest inValue = new FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalRequest();
            inValue.Body = new FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalRequestBody();
            inValue.Body.simpleInterest = simpleInterest;
            inValue.Body.annualInterestRate = annualInterestRate;
            inValue.Body.timeInDays = timeInDays;
            FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalResponse retVal = ((FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap)(this)).CalculatePrincipal(inValue);
            return retVal.Body.CalculatePrincipalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalResponse> FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap.CalculatePrincipalAsync(FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalRequest request) {
            return base.Channel.CalculatePrincipalAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalResponse> CalculatePrincipalAsync(double simpleInterest, double annualInterestRate, double timeInDays) {
            FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalRequest inValue = new FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalRequest();
            inValue.Body = new FinancialCalculatorWebApp.FinCalcReference.CalculatePrincipalRequestBody();
            inValue.Body.simpleInterest = simpleInterest;
            inValue.Body.annualInterestRate = annualInterestRate;
            inValue.Body.timeInDays = timeInDays;
            return ((FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap)(this)).CalculatePrincipalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialCalculatorWebApp.FinCalcReference.CalculateRateResponse FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap.CalculateRate(FinancialCalculatorWebApp.FinCalcReference.CalculateRateRequest request) {
            return base.Channel.CalculateRate(request);
        }
        
        public string CalculateRate(double principalAmount, double simpleInterest, double timeInDays) {
            FinancialCalculatorWebApp.FinCalcReference.CalculateRateRequest inValue = new FinancialCalculatorWebApp.FinCalcReference.CalculateRateRequest();
            inValue.Body = new FinancialCalculatorWebApp.FinCalcReference.CalculateRateRequestBody();
            inValue.Body.principalAmount = principalAmount;
            inValue.Body.simpleInterest = simpleInterest;
            inValue.Body.timeInDays = timeInDays;
            FinancialCalculatorWebApp.FinCalcReference.CalculateRateResponse retVal = ((FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap)(this)).CalculateRate(inValue);
            return retVal.Body.CalculateRateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialCalculatorWebApp.FinCalcReference.CalculateRateResponse> FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap.CalculateRateAsync(FinancialCalculatorWebApp.FinCalcReference.CalculateRateRequest request) {
            return base.Channel.CalculateRateAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialCalculatorWebApp.FinCalcReference.CalculateRateResponse> CalculateRateAsync(double principalAmount, double simpleInterest, double timeInDays) {
            FinancialCalculatorWebApp.FinCalcReference.CalculateRateRequest inValue = new FinancialCalculatorWebApp.FinCalcReference.CalculateRateRequest();
            inValue.Body = new FinancialCalculatorWebApp.FinCalcReference.CalculateRateRequestBody();
            inValue.Body.principalAmount = principalAmount;
            inValue.Body.simpleInterest = simpleInterest;
            inValue.Body.timeInDays = timeInDays;
            return ((FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap)(this)).CalculateRateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialCalculatorWebApp.FinCalcReference.CalculateTimeResponse FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap.CalculateTime(FinancialCalculatorWebApp.FinCalcReference.CalculateTimeRequest request) {
            return base.Channel.CalculateTime(request);
        }
        
        public string CalculateTime(double principalAmount, double simpleInterest, double annualInterestRate) {
            FinancialCalculatorWebApp.FinCalcReference.CalculateTimeRequest inValue = new FinancialCalculatorWebApp.FinCalcReference.CalculateTimeRequest();
            inValue.Body = new FinancialCalculatorWebApp.FinCalcReference.CalculateTimeRequestBody();
            inValue.Body.principalAmount = principalAmount;
            inValue.Body.simpleInterest = simpleInterest;
            inValue.Body.annualInterestRate = annualInterestRate;
            FinancialCalculatorWebApp.FinCalcReference.CalculateTimeResponse retVal = ((FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap)(this)).CalculateTime(inValue);
            return retVal.Body.CalculateTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialCalculatorWebApp.FinCalcReference.CalculateTimeResponse> FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap.CalculateTimeAsync(FinancialCalculatorWebApp.FinCalcReference.CalculateTimeRequest request) {
            return base.Channel.CalculateTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialCalculatorWebApp.FinCalcReference.CalculateTimeResponse> CalculateTimeAsync(double principalAmount, double simpleInterest, double annualInterestRate) {
            FinancialCalculatorWebApp.FinCalcReference.CalculateTimeRequest inValue = new FinancialCalculatorWebApp.FinCalcReference.CalculateTimeRequest();
            inValue.Body = new FinancialCalculatorWebApp.FinCalcReference.CalculateTimeRequestBody();
            inValue.Body.principalAmount = principalAmount;
            inValue.Body.simpleInterest = simpleInterest;
            inValue.Body.annualInterestRate = annualInterestRate;
            return ((FinancialCalculatorWebApp.FinCalcReference.FinancialCalculatorWebServiceSoap)(this)).CalculateTimeAsync(inValue);
        }
    }
}
